### PR TITLE
Sort the Contents of Support and Help Articles by nav_order

### PR DESCRIPTION
**Pull request by vigejolla**

### CODE REVIEW

**Comment by jovirkku** [comment]
Items are first sorted by their nav_order. Looks reasonable to me.

**Comment by jovirkku** [comment]
Looks ok to me. Items are first sorted by nav_order.

**Comment by vigejolla** [comment]
> Looks ok to me. Items are first sorted by nav_order.

I'm going to assume you meant to click the "approve" button instead of "close" :)

**Review by jpwalden — APPROVED** [review]
LGTM

**Review by martyone — APPROVED** [review]

**Pull request merged**
