### PR TITLE
Contents from H1 to H3

### PR DESCRIPTION
**Pull request by jovirkku**
Signed-off-by: Jorma Virkkunen <jorma.virkkunen@jolla.com>

### CODE REVIEW

**Comment by jovirkku** [comment]
Sorry for the commit message: too broad.

**Comment by vigejolla** [comment]
The change itself is fine, but git history is not. Please rebase properly on top of master.

**Comment by jovirkku** [comment]
Any better now?

**Comment by vigejolla** [comment]
> Any better now?

yes, thanks!

**Review by vigejolla — APPROVED** [review]

**Pull request merged**
