### PR TITLE
Remove ChangeLog from Sailfsh X Android build and flash, update OEM blobs mentioned

### PR DESCRIPTION
**Pull request by Thaodan**
- Remove ChangeLog imported from the Wiki, the git history is much better for this
- Update OEM blob file for Android 11 based AOSP flash instructions, V9a based binaries are out and already used everywhere else.

### CODE REVIEW

**Review by llewelld — APPROVED** [review]
The change looks good to me.

As a side note though, it's not clear to me whether this is the changelog for the documentation (in which case, shouldn't the git history be enough?) or covering all repos related to the 10 III adaptation.

**Comment by Thaodan** [comment]
> The change looks good to me.
> 
> As a side note though, it's not clear to me whether this is the changelog for the documentation (in which case, shouldn't the git history be enough?) or covering all repos related to the 10 III adaptation.

Removed the changelog instead.

**Review by llewelld — APPROVED** [review]
LGTM!

**Comment by Thaodan** [comment]
Fixed a small typo.

**Review by llewelld — APPROVED** [review]
Still LGTM!

**Pull request merged**
