### PR TITLE
Combine "Supported Devices" and "Release" into single "Support" box

### PR DESCRIPTION
**Pull request by vigejolla**

### CODE REVIEW

**Comment by vigejolla** [comment]
First attempt. Please review using local Jekyll instance, as that's probably the only way to really see how the page looks like.

**Comment by jovirkku** [comment]
If I got it right (on Jekyll), it looks like this:

**Support**

Contents
1.     Releases
2.     Help Articles
3.     Supported Devices

==> Ok.

**Comment by vigejolla** [comment]
> If I got it right (on Jekyll), it looks like this:
> 
> **Support**
> 
> Contents
> 
>     1. ```
>        Releases
>        ```
> 
>     2. ```
>        Help Articles
>        ```
> 
>     3. ```
>        Supported Devices
>        ```
> 
> 
> ==> Ok.

You are looking at wrong page, or you are commenting on a wrong PR (maybe confused with PR#170) :) This PR is about the very front page page on the documentation site. There you should now see a box with texts "Support" and "Help articles, supported devices and public Sailfish OS releases.".

**Review by jovirkku — APPROVED** [review]
No comments.

**Review by rainemak — APPROVED** [review]

**Pull request merged**
