### PR TITLE
Importing contacts to Sailfish device

### PR DESCRIPTION
**Pull request by jovirkku**
Signed-off-by: Jorma Virkkunen <jorma.virkkunen@jolla.com>

### CODE REVIEW

**Comment by jovirkku** [comment]
A comment for myself:  We need to take this bug into account: https://bz.jollamobile.com/show_bug.cgi?id=59302, i.e. Microsoft 356.

**Comment by jpwalden** [comment]
Looks good, however on line 297 and 299 this word is used: "catenation", that doesn't seem to be a known word, should that be concatenation?

**Comment by jovirkku** [comment]
> on line 297 and 299 this word is used: "catenation"
Hmm, that must be because I simplified the document by cutting off the instructions for merging multiple vcf contacts to one file. All recent phones do that automatically. I failed to notice those words. I'll fix this to the next commit.

**Comment by vigejolla** [comment]
> > on line 297 and 299 this word is used: "catenation"
> > Hmm, that must be because I simplified the document by cutting off the instructions for merging/concatenating multiple vcf contacts into one file. All recent phones do that automatically. I failed to notice those words. I'll fix this in the next commit.
> 
> And yes, the correct noun in this context is 'concatenation' (not 'catenation').

Now you just removed the whole offending paragraph, did you do that on purpose?

**Comment by jovirkku** [comment]
> > > on line 297 and 299 this word is used: "catenation"
> > > Hmm, that must be because I simplified the document by cutting off the instructions for merging/concatenating multiple vcf contacts into one file. All recent phones do that automatically. I failed to notice those words. I'll fix this in the next commit.
> > 
> > 
> > And yes, the correct noun in this context is 'concatenation' (not 'catenation').
> 
> Now you just removed the whole offending paragraph, did you do that on purpose?

Yes, I do not think the concatenation is needed anymore.  "All phones" seem to be able to merge the contacts into one vcf file. Given this, there should not be concatenation issues now.

**Comment by jovirkku** [comment]
Relative links used (docs.sailfishos.org)

**Review by vigejolla — APPROVED** [review]

**Pull request merged**
