### PR TITLE
Bluetooth pairing

### PR DESCRIPTION
**Pull request by jovirkku**
Signed-off-by: Jorma Virkkunen <jorma.virkkunen@jolla.com>

### CODE REVIEW

**Comment by jovirkku** [comment]
I have no more changes for this in my mind.

**Review by jpwalden — APPROVED** [review]
Document looks good to me, however we have now ran out of the numbers on the nav order, the number 14 is already in use and numbers around it as well, so those needs to be adjusted

**Comment by vigejolla** [comment]
> Document looks good to me, however we have now ran out of the numbers on the nav order, the number 14 is already in use and numbers around it as well, so those needs to be adjusted

It's even worse, we have accidentally already used 14 twice, for both "Backup Extraction" and "Battery Lifetime". @jovirkku could you make some room here? Preferably in a separate commit.

**Comment by jovirkku** [comment]
Android App Support: 10
Backup Extraction: 14 (NOTE)
Backup and Restore: 13  (NOTE)
Battery Lifetime: 14
Bluetooth Pairing: 14
Collecting logs with Logcat: 15

It has been "broken" already before my commit. Fixing the indexes requires touching 10-20 documents. But it is doable, of course.

**Comment by vigejolla** [comment]
> It has been "broken" already before my commit. Fixing the indexes requires touching 10-20 documents. But it is doable, of course.

That is well understood. Still, it would be easiest to just fix it here instead of opening a new task for it. But for the sake of clarity it's still best to make those changes in a separate commit.

**Comment by jovirkku** [comment]
> > It has been "broken" already before my commit. Fixing the indexes requires touching 10-20 documents. But it is doable, of course.
> 
> That is well understood. Still, it would be easiest to just fix it here instead of opening a new task for it. But for the sake of clarity it's still best to make those changes in a separate commit.

https://bz.jollamobile.com/show_bug.cgi?id=59444

**Comment by vigejolla** [comment]
> https://bz.jollamobile.com/show_bug.cgi?id=59444

Ok, let's finish that one first and then rebase this PR on top of that, if that's ok with you?

**Comment by jovirkku** [comment]
> > https://bz.jollamobile.com/show_bug.cgi?id=59444
> 
> Ok, let's finish that one first and then rebase this PR on top of that, if that's ok with you?

Yes, ok.

**Comment by jovirkku** [comment]
Nav_order fixed.

**Review by vigejolla — APPROVED** [review]

**Pull request merged**
