### PR TITLE
Add subfolder "Managing Sailfish OS" and move related docs into it

### PR DESCRIPTION
**Pull request by jovirkku**
New subfolder Support/Help_articles/Managing_Sailfish_OS/was created and the README for it.

The following existing docs were moved into Support/Help_articles/Managing_Sailfish_OS/

1. Support/Help_Articles/Checklist_for_Sailfish_OS/
2. Support/Help_Articles/Flashing_Troubleshooting/
3. Support/Help_Articles/Reinstalling_Sailfish_OS/
4. Support/Help_Articles/Updating_Sailfish_OS/
5. Support/Help_Articles/Updating_Vendor_Image/
6. Support/Help_Articles/Publishing_Sailfish_OS_Updates/

The following stub document was added:

7. Support/Help_Articles/Managing_Sailfish_OS/Installing_Sailfish_OS/

### CODE REVIEW

**Review by vigejolla — CHANGES_REQUESTED** [review]
Please add redirects from old locations to new ones. For example, in /Support/Help_Articles/Checklist_for_Sailfish_OS/ you would have the following contents in README.md:
```
---
title: Checklist for Sailfish OS
permalink: Support/Help_Articles/Checklist_for_Sailfish_OS/
layout: default
nav_exclude: true
redirect_to: /Support/Help_Articles/Managing_Sailfish_OS/Checklist_for_Sailfish_OS/
---
```

**Review by jpwalden — COMMENTED** [review]
Looks good to me, added installing part is good and compact and it is nicely linked to our official instructions since it is good to use those and not repeat steps here. Redirecting proposed by Ville is a good idea.

**Comment by jovirkku** [comment]
> For example, in /Support/Help_Articles/Checklist_for_Sailfish_OS/ you would have the following contents in README.md:

I have removed all those old directories...

**Comment by vigejolla** [comment]
> I have removed all those old directories...

Just add them back :)

**Review by vigejolla — APPROVED** [review]
LGTM. But please next time add the redirects in a separate commit as it makes reviewing easier. Didn't matter this time as we had already reviewed the contents before you added the redirects.

**Pull request merged**
