### PR TITLE
Add redirection functionality to default layout

### PR DESCRIPTION
**Pull request by vigejolla**
Redirection can be used with a simple redirect_to line in front matter.

### CODE REVIEW

**Review by jovirkku — APPROVED** [review]
This looks ok to me on principal level -- I do not know how to test this easily.

**Comment by vigejolla** [comment]
> This looks ok to me on principal level -- I do not know how to test this easily.

You can test with local jekyll instance, just follow the instructions in README.md. e.g. Create a directory  Support/Help_Articles/Android_App_Support/Test, place README.md there, with these lines on top:
```
---
permalink: Support/Help_Articles/Android_App_Support/Test
parent: Android App Support
redirect_to: /Support/Help_Articles/Android_App_Support/Aptoide
layout: default
nav_order: 1000
---
```
Open http://localhost:4000/Support/Help_Articles/Android_App_Support/Test and end up on the aptoide page.

**Comment by jovirkku** [comment]
This redirection mechanism appears to work. I tested it after getting the instructions from vige.

**Review by sledges — APPROVED** [review]
All good:)

**Pull request merged**
